lib/megalithic_web/router.ex
defmodule MegalithicWeb.Router do
  use MegalithicWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MegalithicWeb, host: "setup." do
    pipe_through :browser

    get "/", PageController, :setup
  end

  # scope "/", MegalithicWeb, host: "stats." do
  #   pipe_through :browser
  # end

  scope "/", MegalithicWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/about", PageController, :about
    get "/canon", PageController, :canon
    get "/mercantile", PageController, :mercantile
    get "/setup", PageController, :setup
    get "/thoughts", BlogPostController, :index
    get "/thoughts/:slug", BlogPostController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", MegalithicWeb do
  #   pipe_through :api
  # end
end

lib/megalithic/application.ex
defmodule Megalithic.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    children = [
      MegalithicWeb.Endpoint,
      worker(Megalithic.BlogService, [])
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Megalithic.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MegalithicWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/megalithic/blog_post.ex
defmodule Megalithic.BlogPost do
  defstruct slug: "",
            title: "",
            date: "",
            intro: "",
            content: "",
            image: "",
            keywords: ""

  def compile(file) do
    post = %Megalithic.BlogPost{
      slug: file_to_slug(file)
    }

    :code.priv_dir(:megalithic)
    |> Path.join(["posts/", file])
    |> File.read!()
    |> split
    |> extract(post)
  end

  defp file_to_slug(file) do
    String.replace(file, ~r/\.md$/, "")
  end

  defp split(data) do
    [frontmatter, markdown] = String.split(data, ~r/\n-{3,}\n/, parts: 2)
    {parse_yaml(frontmatter), Earmark.as_html(markdown)}
  end

  defp parse_yaml(yaml) do
    [parsed] = :yamerl_constr.string(yaml)
    parsed
  end

  defp extract({props, content}, post) do
    %{
      post
      | title: get_prop(props, "title"),
        date: get_prop(props, "date") |> Calendar.Date.Parse.iso8601!(),
        intro: get_prop(props, "intro"),
        image: get_prop(props, "image") && get_prop(props, "image"),
        content: content,
        keywords: get_prop(props, "keywords") && get_prop(props, "keywords")
    }
  end

  defp get_prop(props, key) do
    case :proplists.get_value(String.to_charlist(key), props) do
      :undefined -> nil
      x -> to_string(x)
    end
  end
end

lib/megalithic/blog_post_retriever.ex
defmodule Megalithic.BlogPostRetriever do
  def retrieve do
    :code.priv_dir(:megalithic)
    |> Path.join("posts")
    |> File.ls!()
    |> Enum.map(&Megalithic.BlogPost.compile/1)
    |> Enum.sort(&sort/2)
  end

  def sort(a, b) do
    Calendar.Date.diff(a.date, b.date) > 0
  end
end

lib/megalithic/blog_service.ex
defmodule Megalithic.BlogService do
  use GenServer

  def start_link do
    GenServer.start_link(__MODULE__, :ok, name: __MODULE__)
  end

  def init(:ok) do
    posts = Megalithic.BlogPostRetriever.retrieve()
    {:ok, posts}
  end

  def handle_call({:list}, _from, posts) do
    {:reply, {:ok, posts}, posts}
  end

  def handle_call({:get_by_slug, slug}, _from, posts) do
    case Enum.find(posts, fn p -> p.slug == slug end) do
      nil -> {:reply, :not_found, posts}
      post -> {:reply, {:ok, post}, posts}
    end
  end

  def list() do
    GenServer.call(__MODULE__, {:list})
  end

  def get_by_slug(slug) do
    GenServer.call(__MODULE__, {:get_by_slug, slug})
  end
end

lib/mix/tasks/sitemap.ex
defmodule Mix.Tasks.Sitemap do
  @moduledoc """
  Generates a static sitemap.
  """

  use Mix.Task

  def run(_) do
    # Don't require a running HTTP server
    Application.put_env(:phoenix, :serve_endpoints, false, persistent: true)

    # Don't start any repos
    Application.put_env(:megalithic, :ecto_repos, [])

    # Start the application
    Mix.Task.run("app.start", [])

    # Start the Sitemap process
    Sitemap.start(nil, nil)

    # Generate the sitemap
    MegalithicWeb.Sitemap.generate()
  end
end

lib/megalithic_web/controllers/blog_post_controller.ex
defmodule MegalithicWeb.BlogPostController do
  use MegalithicWeb, :controller

  def index(conn, _params) do
    {:ok, posts} = Megalithic.BlogService.list()
    render(conn, "index.html", posts: posts)
  end

  def show(conn, %{"slug" => slug}) do
    case Megalithic.BlogService.get_by_slug(slug) do
      {:ok, post} ->
        render(conn, "show.html",
          post: post,
          title: post.title,
          description: post.intro,
          keywords: post.keywords
        )

      :not_found ->
        not_found(conn)
    end
  end

  def not_found(conn) do
    conn
    |> put_status(:not_found)
    |> render(Megalithic.ErrorView, "404.html")
  end
end

lib/megalithic_web/controllers/page_controller.ex
defmodule MegalithicWeb.PageController do
  use MegalithicWeb, :controller

  def index(conn, _params) do
    {:ok, posts} = Megalithic.BlogService.list()
    render(conn, "index.html", posts: posts)
  end

  def about(conn, _params) do
    render(conn, "about.html")
  end

  def canon(conn, _params) do
    render(conn, "canon.html")
  end

  def setup(conn, _params) do
    render(conn, "setup.html")
  end

  def mercantile(conn, _params) do
    render(conn, "mercantile.html")
  end
end

lib/megalithic_web/views/blog_post_view.ex
defmodule MegalithicWeb.BlogPostView do
  use MegalithicWeb, :view
end

lib/megalithic_web/views/error_view.ex
defmodule MegalithicWeb.ErrorView do
  use MegalithicWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/megalithic_web/views/layout_view.ex
defmodule MegalithicWeb.LayoutView do
  use MegalithicWeb, :view

  def robots(conn) do
    case conn.assigns[:robots] do
      nil -> "INDEX,FOLLOW"
      robots -> robots
    end
  end

  def title(conn) do
    case conn.assigns[:title] do
      nil -> "megalithic industries"
      title -> "#{title} | megalithic industries"
    end
  end

  def description(conn) do
    case conn.assigns[:description] do
      nil -> ""
      description -> description
    end
  end

  def keywords(conn) do
    case conn.assigns[:keywords] do
      nil ->
        "irc,weechat,wechat,whatsapp,rtc,freenode,wee-chat,slack,bitlbee,google,hangouts,google hangouts,wee-slack,wee_slack,weeslack,python,purple,gtalk,jabber,xmpp,digital ocean,droplet,do,znc,bouncer,ubuntu,18.04,setup,connect,setup,config,configurations,connections,service,services,ubuntu 18.04,ubuntu 16.04,daemon,websocket,websockets,api,real time chat,real-time,cli,command,command-line,interface,command line interface,tool,tools,oss,opensource,open-source,open source,github,git,version control,mercurial,hg,vcs,dotfiles,dots,files,python,pip,readme,systemd,initd,etc,mac,apple,macos,mojave,sierra,high sierra,macosx,osx,mac os,mac osx,chat,token,register,registration,megalithic,megalith,megalithic industries,monolith,easter island,design,designer,phoenix,elixir,vim,tmux,nvim,neovim,development,software,engineering,software engineer,developer,front-end,front end,back-end,back end,server,ssh,secure shell,secure,shell,zsh,bash,sh,fish,z-shell"

      keywords ->
        keywords
    end
  end
end

lib/megalithic_web/views/page_view.ex
defmodule MegalithicWeb.PageView do
  use MegalithicWeb, :view
end

lib/megalithic_web/templates/blog_post/index.html.eex
<%= if @posts != nil and Enum.count(@posts) > 0 do %>
  <section class="mw8 center">
    <h2 class=" fw1 pv2">thoughts</h2>
    <%= for post <- @posts do %>
      <article class="bt bb b--black-10">
        <a class="db pv4 no-underline black dim" href="<%= Routes.blog_post_path(@conn, :show, post.slug) %>">
          <div class="flex flex-column flex-row-ns">
            <div class="w-100">
              <h1 class="f4 fw1 mt0 lh-title ttc"><%= post.title %></h1>
              <p class="f6 f5-l lh-copy"><%= post.intro %></p>
              <time class="f6 db gray"><%= post.date |> Calendar.Strftime.strftime!("%h %e %Y") %></time>
            </div>
          </div>
        </a>
      </article>
    <% end %>
  </section>
<% end %>

lib/megalithic_web/templates/blog_post/show.html.eex
<h2 class="fw1 pv2">thoughts</h2>
<article class="cf pv4 bt b--black-10">
  <header class="fn fl-ns w-40-ns pr4-ns">
    <h1 class="fw1 f4 mb1 mt0 lh-title post-title ttc"><%= @post.title %></h1>
    <time class="f6 ttu tracked gray post-date"><%= @post.date |> Calendar.Strftime.strftime!("%h %e %Y") %></time>
  </header>
  <div class="fn fl-ns w-60-ns post-content">
    <%= raw(elem(@post.content, 1)) %>
  </div>
</article>

lib/megalithic_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="ROBOTS" content="<%= robots(@conn) %>">
    <meta name="keywords" content="<%= keywords(@conn) %>">
    <meta name="description" content="<%= description(@conn) %>">
    <title><%= title(@conn) %></title>
    <link href="https://fonts.googleapis.com/css?family=Inconsolata:400,700" rel="stylesheet">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.1/styles/default.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.1/highlight.min.js"></script>
    <%# <script>hljs.initHighlightingOnLoad();</script> %>
    <script type="text/javascript">
      document.addEventListener('DOMContentLoaded', (event) => {
        document.querySelectorAll('pre code').forEach((block) => {
          hljs.highlightBlock(block);
        });
      });
    </script>
  </head>
  <body class="pa4-l normal">
    <div class"bg-white h-100 pa3 ph0-l pv6-l">
      <div class="center mw8">
        <header class="pa3 pa0-ns">
          <section class="container">
            <div class="w-100 db">
              <nav class="tc tl-ns w-100">
                <a href="/" class="link highlight-link hover-light-silver f4">megalithic industries</a>
                <ul class="fn fr-ns list dib ma0 pa0 mt3 mt0-ns tc center w-100 w-auto-ns">
                  <li class="dib mr2-ns pa2 pa0-ns"><a href="/thoughts/" class="link hover-gold">thoughts</a></li>
                  <li class="dib mr2-ns pa2 pa0-ns">○</li>
                  <li class="dib mr2-ns pa2 pa0-ns"><a href="/canon/" class=" link hover-gold">canon</a></li>
                  <li class="dib mr2-ns pa2 pa0-ns">○</li>
                  <li class="dib mr2-ns pa2 pa0-ns"><a href="/mercantile/" class=" link hover-gold">mercantile</a></li>
                  <li class="dib mr2-ns pa2 pa0-ns">○</li>
                  <li class="dib mr2-ns pa2 pa0-ns"><a href="/about/" class=" link hover-gold">about</a></li>
                </ul>
              </nav>
            </div>
          </section>
        </header>
        <main role="main" class="ph3 ph0-l container">
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

          <%= render @view_module, @view_template, assigns %>
        </main>
        <footer class="pv5 pv6-l tc tl-ns">
          <p class="f6"><span class="dib mr4 mr5-ns">&copy; <%= DateTime.utc_now().year %> megalithic industries</span>
            <%# <a class="link hover-gold" href="https://www.github.com/megalithic" title="github">github</a> / %>
            <%# <a class="link hover-gold" href="https://www.twitter.com/megalithic" title="twitter">twitter</a> / %>
            <%# <a class="link hover-gold" href="https://www.instagram.com/megalithic" title="instagram">instagram</a> / %>
            <%# <a class="link hover-gold" href="mailto:seth.messer@gmail.com" title="email">email</a> / %>
          </p>
        </footer>
      </div>
    </div>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <script async="" src="//stats.megalithic.io/tracker.js" id="fathom-script"></script>
    <script type="text/javascript">
      (function(f, a, t, h, o, m){
        a[h]=a[h]||function(){
          (a[h].q=a[h].q||[]).push(arguments)
        };
        o=f.createElement('script'),
        m=f.getElementsByTagName('script')[0];
        o.async=1; o.src=t; o.id='fathom-script';
        m.parentNode.insertBefore(o,m)
      })(document, window, '//stats.megalithic.io/tracker.js', 'fathom');
      fathom('set', 'siteId', 'ARYBF');
      fathom('trackPageview');
    </script>
  </body>
</html>

lib/megalithic_web/templates/page/about.html.eex
<section class="mw8 center">
  <h2 class=" fw1 pv2">about</h2>
  <div class="mt1 mb4 relative top--1-l measure-wide measure-narrow-ns fr-l">
    <blockquote class="pa0 ml0 b"><em>"I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else."</em></blockquote>
    <cite class="highlight-header">- C.S. Lewis</cite>
  </div>

  <div class="mt4 mt2-ns">
    <p class="f4 tl measure lh-copy p">
      Hiya, Seth here. I presently work as a remote software engineer based out of Birmingham, AL for <a href="https://enbala.com" title="enbala" target="_blank" rel="noopener noreferrer">Enbala</a>,
      building software for distributed and alternative energy. I get to play with awesome tech such as <a href="https://elixir-lang.org" title="elixir-lang" target="_blank" rel="noopener noreferrer">elixir-lang</a>, <a href="https://elm-lang.org" title="elm-lang" target="_blank" rel="noopener noreferrer">elm-lang</a>, and <a href="https://graphql.org" title="graphql" target="_blank" rel="noopener noreferrer">graphql</a>.
    </p>

    <p class="f4 tl measure lh-copy p">
      Being an Industrial Design grad from <a href="http://cadc.auburn.edu/design/design-degrees-programs/indd" title="Auburn University Industrial Design" target="_blank" rel="noopener noreferrer">Auburn University</a>, you know I'm
      into making stuff (wood working, 3d printing, home automation things, etc). Check out my <a href="https://instagram/megalithic" title="instagram @megalithic" target="_blank" rel="noopener noreferrer">instagram feed</a> for project pics.
    </p>

    <p class="f4 tl measure lh-copy p">
      I have a pretty rad German Shepherd mix, named <a href="https://www.instagram.com/p/BNC3irCA_xuQN6me9cTvPngAo54ZPovSgC1DO80" title="Kona!" target="_blank" rel="noopener noreferrer">Kona</a>.
    </p>

    <p class="f4 tl measure lh-copy p">
      Also, I have an unhealthy obsession with <a href="https://github.com/megalithic/dotfiles" title="dotfiles!" target="_blank" rel="noopener noreferrer">dotfiles</a>.
    </p>
    <p class="tc w-100 w-55-ns f4">∞</p>

    <%# <p class="f4 tl measure lh-copy p tc"> %>
    <%#   <img class="w-50 br3" src="<%= Routes.static_path(@conn, "/images/kona.jpg") %1>" alt="kona!" /> %>
    <%# </p> %>
  </div>

  <div class="mt5">
    <header class="fn w-50-ns pr4-ns">
      <h1 class="fw1 f4 mb1 mt0 lh-title">get at me...</h1>
    </header>

    <p class="mt2">
      <span class="b mr2"><a href="https://www.github.com/megalithic" title="github@megalithic" class="link" target="_blank" rel="noopener noreferrer">github</a></span>
      <span class="b mr2"><a href="https://www.twitter.com/megalithic" title="twitter@megalithic" class="link" target="_blank" rel="noopener noreferrer">twitter</a></span>
      <span class="b mr2"><a href="https://www.instagram.com/megalithic" title="instagram@megalithic" class="link" target="_blank" rel="noopener noreferrer">instagram</a></span>
      <span class="b mr2"><a href="mailto:seth.messer@gmail.com" title="seth.messer@gmail.com" class="link" target="_blank" rel="noopener noreferrer">email</a></span>
    </p>
  </div>
</section>

lib/megalithic_web/templates/page/canon.html.eex
<section class="mw8 center">
  <h2 class="fw1 pv2">canon</h2>
  <div class="mt2">
    <p class="p f4 tl measure-narrow lh-copy">
      coming soon..
    </p>
  </div>

lib/megalithic_web/templates/page/index.html.eex
<%= if @posts != nil and Enum.count(@posts) > 0 do %>
  <section class="mw8 center">
    <h2 class="fw1 pv2">thoughts</h2>
    <%= for post <- @posts do %>
      <article class="bt bb b--black-10">
        <a class="db pv4 no-underline black dim" href="<%= Routes.blog_post_path(@conn, :show, post.slug) %>">
          <div class="flex flex-column flex-row-ns">
            <div class="w-100">
              <h1 class="f4 fw1 mt0 lh-title ttc"><%= post.title %></h1>
              <p class="f6 f5-l lh-copy"><%= post.intro %></p>
              <time class="f6 db gray"><%= post.date |> Calendar.Strftime.strftime!("%h %e %Y") %></time>
            </div>
          </div>
        </a>
      </article>
    <% end %>
  </section>
<% end %>

lib/megalithic_web/templates/page/mercantile.html.eex
<section class="mw8 center">
  <h2 class="fw1 pv2">mercantile</h2>
  <div class="mt2">
    <p class="p f4 tl measure-narrow lh-copy">
    <a href="https://www.etsy.com/shop/MegalithicMercantile" target="_blank">Megalithic Mercantile Etsy Shop</a>
    <a href="https://www.facebook.com/megalithic.mercantile" target="_blank">Megalithic Mercantile Facebook Page</a>
    </p>
  </div>

lib/megalithic_web/templates/page/setup.html.eex
<section class="mw8 center">
  <h2 class="fw1 pv2">setup</h2>
  <div class="mt2">
    <p class="p f4 tl measure-narrow lh-copy">
      coming soon..
    </p>
  </div>